#!/usr/bin/env python3
"""
APIGuard CLI for CI/CD Integration
==================================
Serves as the DevSecOps wrapper for the pipeline.
Returns an exit code of 1 if Critical or High vulnerabilities are found,
effectively failing the GitHub Actions build and blocking deployment.
"""

import sys
import argparse
from main import run as run_main

def run_pipeline(target_url: str, spec_file: str):
    print(f"[+] APIGuard Enterprise CI/CD Pipeline Agent Executing...")
    print(f"[+] Target: {target_url}")
    print(f"[+] Specification: {spec_file}")
    
    print("[+] Initiating parsing and cognitive fuzzing sequences...")
    
    try:
        class Args:
            url = target_url
            spec = spec_file
            token_a = "Bearer CI_CD_TEST_TOKEN"
            id_a = "ci_user"
            id_b = "ci_attacker"
            low_priv_token = None
            admin_token = None
            auth_token = None
            output = None
            html = None
            pdf = None
            history_db = "apiguard_history.db"
            no_history = True
            timeout = 10
            delay = 0.1
            rate_requests = 50
        
        results = run_main(Args())
        
        # Read the aggregated metrics generated by the dashboard module inside run()
        # Since `run()` returns the raw report dict from memory, we must parse the modules
        critical_count = 0
        high_count = 0
        
        for mod_name, mod_data in results.get("modules", {}).items():
            if isinstance(mod_data, dict) and "findings" in mod_data:
                for finding in mod_data["findings"]:
                    sev = finding.get("severity", "").upper()
                    if sev == "CRITICAL":
                        critical_count += 1
                    elif sev == "HIGH":
                        high_count += 1
        
        print("\n================ APIGuARD REPORT ================")
        print(f"  Critical Vulnerabilities : {critical_count}")
        print(f"  High Vulnerabilities     : {high_count}")
        print("=================================================")
        
        if critical_count > 0 or high_count > 0:
            print("\n[FAILED] Security Gate failed. Vulnerabilities detected.")
            print("[FAILED] Halting CI/CD pipeline to prevent vulnerable deployment.")
            sys.exit(1) # Return exit code 1 to break the build
            
        print("\n[SUCCESS] Security Gate passed. No critical/high vulnerabilities found.")
        sys.exit(0) # Return exit code 0 to allow deployment
        
    except Exception as e:
        print(f"[ERROR] Pipeline scanner encountered a fatal failure: {e}")
        sys.exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="APIGuard CI/CD Agent")
    parser.add_argument("--url", required=True, help="Target application URL")
    parser.add_argument("--spec", help="OpenAPI Spec file path")
    
    args = parser.parse_args()
    run_pipeline(args.url, args.spec)
